# This is a basic workflow to help you get started with Actions

name: CI-Nodejs

# 触发条件，什么条件开始，并列表示多个触发条件
on:
  # 推送代码到主分支上触发
  push:
    branches: [ main ]
  schedule:
  # 东八区正确设置时间 (x-8)>0?(x-8):(x-8+24)
    - cron: '40 21 * * *'
  #pull_request:  # 从主分支上拉取时触发
   # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # 这个工作流包含一个单独的工作叫作“构建”
  build:
    # The type of runner that the job will run on
    # 这个运行者所需的环境时最新的ubunt系统
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Checkout codes'
      # 拷贝器，从GitHub上拷贝仓库代码
        uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Setup Node.js environment'
      # 设置运行环境 这里是node
        uses: actions/setup-node@v2.1.5
        with:
        # 指定环境的版本
          node-version: '14.x'
      - name: 'install axios'
        run: npm install axios
      - name: 'install cheerio'
        run: npm install cheerio
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: node index.js ${{ secrets.PARA_URL }}
        # run: node ./src/test.js 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.